export const DEALS_ARE_LOADING = "DEALS_ARE_LOADING";
export const DEALS_ARE_NOT_LOADING = "DEALS_ARE_NOT_LOADING";
export const DEALS_ARE_REFRESHING = "DEALS_ARE_REFRESHING";
export const DEALS_ARE_NOT_REFRESHING = "DEALS_ARE_NOT_REFRESHING";
