export const LOCATIONS_ARE_LOADING = "LOCATIONS_ARE_LOADING";
export const LOCATIONS_ARE_NOT_LOADING = "LOCATIONS_ARE_NOT_LOADING";
export const LOCATIONS_ARE_REFRESHING = "LOCATIONS_ARE_REFRESHING";
export const LOCATIONS_ARE_NOT_REFRESHING = "LOCATIONS_ARE_NOT_REFRESHING";
