export const USER_IS_LOGGING_IN = "USER_IS_LOGGING_IN";
export const USER_IS_NOT_LOGGING_IN = "USER_IS_NOT_LOGGING_IN";
export const USER_IS_REGISTERING = "USER_IS_REGISTERING";
export const USER_IS_NOT_REGISTERING = "USER_IS_NOT_REGISTERING";
