export const USER_IS_LOGGING_IN = "USER_IS_LOGGING_IN";
export const USER_IS_NOT_LOGGING_IN = "USER_IS_NOT_LOGGING_IN";
export const USER_IS_REGISTERING = "USER_IS_REGISTERING";
export const USER_IS_NOT_REGISTERING = "USER_IS_NOT_REGISTERING";
export const USER_IS_REQUESTING_RECOVERY_CODE =
  "USER_IS_REQUESTING_RECOVERY_CODE";
export const USER_IS_NOT_REQUESTING_RECOVERY_CODE =
  "USER_IS_NOT_REQUESTING_RECOVERY_CODE";
