export const USER_IS_LOGGING_IN = "USER_IS_LOGGING_IN";
export const USER_IS_NOT_LOGGING_IN = "USER_IS_NOT_LOGGING_IN";
export const USER_IS_REGISTERING = "USER_IS_REGISTERING";
export const USER_IS_NOT_REGISTERING = "USER_IS_NOT_REGISTERING";
export const USER_IS_REQUESTING_RECOVERY_CODE =
  "USER_IS_REQUESTING_RECOVERY_CODE";
export const USER_IS_NOT_REQUESTING_RECOVERY_CODE =
  "USER_IS_NOT_REQUESTING_RECOVERY_CODE";
export const USER_IS_CHANGING_PASSWORD = "USER_IS_CHANGING_PASSWORD";
export const USER_IS_NOT_CHANGING_PASSWORD = "USER_IS_NOT_CHANGING_PASSWORD";
export const USER_IS_UPDATING = "USER_IS_UPDATING";
export const USER_IS_NOT_UPDATING = "USER_IS_NOT_UPDATING";
export const USER_MESSAGE_IS_SENDING = "USER_MESSAGE_IS_SENDING";
export const USER_MESSAGE_IS_NOT_SENDING = "USER_MESSAGE_IS_NOT_SENDING";
