export const formFields = {
  registerFirstName: "firstName",
  registerLastName: "lastName",
  registerEmail: "email",
  registerPhoneNumber: "phoneNumber",
  registerPassword: "password",
  forgotPasswordPhoneNumber: "phoneNumber",
  changePasswordRecoveryCode: "recoveryCode",
  changePasswordCurrentPassword: "currentPassword",
  changePasswordPassword: "password",
  changePasswordConfirmPassword: "confirmPassword",
  updatePersonalInfoFirstName: "firstName",
  updatePersonalInfoLastName: "lastName",
  updatePersonalInfoEmailName: "email",
  updatePersonalInfoPhoneNumber: "phoneNumber",
};
